### ISSUE TITLE
maven forbidden

### ISSUE THREAD

**Issue by axaluss** [phillord/hermit-maven#1]
when i try to access http://homepages.cs.ncl.ac.uk/phillip.lord/maven/org/semanticweb/hermit/HermiT/1.3.7.1/HermiT-1.3.7.1.pom

i get a 

Forbidden

You don't have permission to access /phillip.lord/maven/org/semanticweb/hermit/HermiT/1.3.7.1/HermiT-1.3.7.1.pom on this server.

**Comment by phillord** [comment]
Oops. Fixed.

Thanks for letting me know.

**Comment by axaluss** [comment]
It would be nice to supply also a sources jar file in the maven repositories.

**Comment by ansell** [comment]
I use the following to add the test-jar file and get sources for both the jar file and the tests:

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.2</version>
                <executions>
                    <execution>
                        <id>attach-source</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>attach-test-sources</id>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by axaluss** [comment]
i am using SBT. 
It supports source and javadoc download but it doesn't get your sources

resolvers += "phillord" at "http://homepages.cs.ncl.ac.uk/phillip.lord/maven"
libraryDependencies ++= Seq(
    "net.sourceforge.owlapi" % "owlapi-impl" % "3.4.3" withSources() withJavadoc(),
    "net.sourceforge.owlapi" % "owlapi-api" % "3.4.3" withSources() withJavadoc(),
    "net.sourceforge.owlapi" % "owlapi-apibinding" % "3.4.3" withSources() withJavadoc(),
    "org.scalatest" % "scalatest_2.10" % "1.9.1" % "test" withSources() withJavadoc(),
    "postgresql" % "postgresql" % "9.1-901-1.jdbc4"  withSources() withJavadoc(),
    "org.squeryl" %% "squeryl" % "0.9.5-6" withSources() withJavadoc(),
    "org.semanticweb.hermit" % "HermiT" % "1.3.7.1" withSources() withJavadoc() // doesnt work. throws exception. expects sources jar and javadoc jar
)

**Comment by phillord** [comment]
I'll add this as soon as I can, and do a new point release.
