### ISSUE TITLE
Hermit 1.3.8

### ISSUE THREAD

**Issue by aindlq** [phillord/hermit-maven#3]
Could you please publish artifact for latest Hermit release - v1.3.8.

**Comment by phillord** [comment]
I will try and do so; I'm hoping to delete this repo soon, and move it
to the main hermit svn, but as a 1.3.9 release could be any time away,
you are correct this is probably worth doing.

Phil

artemkozlov notifications@github.com writes:

> Could you please publish artifact for latest Hermit release - v1.3.8.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/phillord/hermit-maven/issues/3

## 

Phillip Lord,                           Phone: +44 (0) 191 222 7827
Lecturer in Bioinformatics,             Email: phillip.lord@newcastle.ac.uk
School of Computing Science,            http://homepages.cs.ncl.ac.uk/phillip.lord
Room 914 Claremont Tower,               skype: russet_apples
Newcastle University,                   twitter: phillord
NE1 7RU

**Comment by phillord** [comment]
The hermit-reasoner repo is now open and available in central
