### ISSUE TITLE
ConcurrentModificationException when using multiple HermiT instances

### ISSUE THREAD

**Issue by pbonte** [phillord/hermit-maven#4]
Hi,

I use multiple HermiT instances with multiple OWLOntologies in different threads. A ConcurrentModificationException is sometimes thrown when flushing one of  the reasoners, on the same time axioms are added to another ontology. 
This is due to the fact that my OWLOntologyManager manges multiple ontologies and since Hermit is registered as OntologyChanges listener it will receive all the updates from all the ontologies.

When flushing, the ontology changes are iterated, but in some cases the list changes because new axioms are added in another ontology.

I fixed this by checking in the ontologiesChanged method if the changes are destined for the ontology linked to the reasoner, instead of in the flush method.

This solves my problem.

Kind regards,
Pieter

**Comment by phillord** [comment]
Unfortunately, this repository is only a mirror of the main repo that I use for integration testing of the maven build. It's a one way process, though -- nothing goes back from here.

Bugs in anything other than the mavenization need to be reported to the upstream developers.

https://groups.google.com/forum/#!forum/hermit-users
https://code.google.com/p/hermit-reasoner/issues/list
